server:
  port: 8081
spring:
  application:
    name: spring-cloud-nacos-consumer

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.179.128:8848
        namespace: 4a338e19-f4fd-42fc-a2c0-80d3ae68d382
